### ISSUE TITLE
Is there a function to save the history of changes?

### ISSUE THREAD

**Issue by starfoxik** [finanalyst/grav-plugin-persistent-data#1]
I want to create a form with a history of changes. In one data field I need to enter 2 values and pass them off one by one as a table.

**Comment by finanalyst** [comment]
Have you looked at sequential form?

**Comment by starfoxik** [comment]
Not exactly what I need. This creates a form step by step without saving the data. I was add `userinfo: true` in process, but nothing was saved in the file and it seems to me that it will change the data, but not add.
So, is there a way to use this plugin as a change history?

**Comment by finanalyst** [comment]
Sorry for massive delay in response. My github notifications is being sent to spam.  
The purpose of the plugin is to keep some sort of state. Actually, I think it should be a part of the Sessions, but I have not enough information about SESSIONS to get this to work.
A change history would require some form of diff function and logging.   
I've done that for another purpose in ContentEdit. Try looking there.
